<h1>Commits</h1>
<?php if ($this->entities) : ?>
<table class="table">
	<?php foreach ($this->entities as $entity) : ?>
		<tr>
			<td>
				<?php echo $entity->getVersion() ?>
			</td>
			<td>
				<?php echo $this->dateFormat($entity->getTimestamp(), \IntlDateFormatter::SHORT) ?>
			</td>
			<td>
				<?php echo nl2br($this->escapeHtml($entity->getMessage())) ?>
			</td>
			<td>
				<span class="editable editable-key-x" id="key-x" data-pk="<?php echo $this->escapeHtmlAttr($entity->getNodeId()) ?>" data-emptyText="X" data-type="text" data-url="<?php echo $this->url('kofus_versioning', array('controller' => 'commit', 'action' => 'edit-ajax', 'id' => $entity->getNodeId())) ?>"><?php echo $this->escapeHtml($entity->getKeyX()) ?></span>
			</td>
			<td>
				<span class="editable editable-key-y" id="key-y" data-pk="<?php echo $this->escapeHtmlAttr($entity->getNodeId()) ?>" data-emptyText="Y" data-type="text" data-url="<?php echo $this->url('kofus_versioning', array('controller' => 'commit', 'action' => 'edit-ajax', 'id' => $entity->getNodeId())) ?>"><?php echo $this->escapeHtml($entity->getKeyY()) ?></span>
			</td>
			<td>
				<span class="editable editable-key-product" id="product" data-pk="<?php echo $this->escapeHtmlAttr($entity->getProductId()) ?>" data-emptyText="Product" data-type="text" data-url="<?php echo $this->url('kofus_versioning', array('controller' => 'commit', 'action' => 'edit-ajax', 'id' => $entity->getNodeId())) ?>"><?php echo $this->escapeHtml($entity->getProductId()) ?></span>
			</td>
			<td>
				<?php echo $this->escapeHtml($entity->getAuthor()) ?>
			</td>
		</tr>
	<?php endforeach ?>
</table>
<?php else : ?>
	<p>Keine Einträge.</p>
<?php endif ?>